AllCops:
  Exclude:
    - 'bin/*'
    - 'db/**/*'
    - 'vendor/bundle/**/*'

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Exclude:
    - 'spec/**/*'

Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*'

Rails:
  Enabled: true

Rails/FindBy:
  Enabled: false

Style/Documentation:
  Enabled: false
