AllCops:
  Exclude:
    - 'bin/*'
    - 'db/**/*'
    - 'spec/**/*'
    - 'vendor/bundle/**/*'
  RunRailsCops: true

Metrics/LineLength:
  AllowURI: true
  Enabled: false

Style/Documentation:
  Enabled: false

Style/IfUnlessModifier:
  Exclude:
    - 'config/initializers/*'

Style/SingleSpaceBeforeFirstArg:
  Exclude:
    - 'config/puma.rb'

Style/SpaceAroundOperators:
  Exclude:
    - 'config/puma.rb'
