AllCops:
  Exclude:
    - 'bin/*'
    - 'db/**/*'
    - 'spec/**/*'
    - 'vendor/bundle/**/*'

Metrics/LineLength:
  Enabled: false

Rails:
  Enabled: true

Rails/FindBy:
  Enabled: false

Style/Documentation:
  Enabled: false
