os: linux
dist: bionic
language: ruby

services:
  - postgresql

rvm:
  - 2.4.10

addons:
  chrome: stable

cache:
  bundler: true

before_install:
  - LATEST_CHROMEDRIVER_VERSION=`curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE"`
  - curl "https://chromedriver.storage.googleapis.com/${LATEST_CHROMEDRIVER_VERSION}/chromedriver_linux64.zip" -O
  - unzip chromedriver_linux64.zip -d ~/bin

before_script:
  - psql -c 'create database "starterapp_test";' -U postgres
