language: ruby
rvm:
  - 2.2.1
<<<<<<< HEAD
services:
  - mongodb
=======
>>>>>>> @{-1}
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
before_script:
  - bundle exec rake db:mongoid:create_indexes
